# LAB | Imbalanced

**Load the data**

In this challenge, we will be working with Credit Card Fraud dataset.

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv

Metadata

- **distance_from_home:** the distance from home where the transaction happened.
- **distance_from_last_transaction:** the distance from last transaction happened.
- **ratio_to_median_purchase_price:** Ratio of purchased price transaction to median purchase price.
- **repeat_retailer:** Is the transaction happened from same retailer.
- **used_chip:** Is the transaction through chip (credit card).
- **used_pin_number:** Is the transaction happened by using PIN number.
- **online_order:** Is the transaction an online order.
- **fraud:** Is the transaction fraudulent. **0=legit** -  **1=fraud**

In [41]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [42]:
fraud = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv")
fraud.head()

KeyboardInterrupt:

**Steps:**

- **1.** What is the distribution of our target variable? Can we say we're dealing with an imbalanced dataset?
- **2.** Train a LogisticRegression.
- **3.** Evaluate your model. Take in consideration class importance, and evaluate it by selection the correct metric.
- **4.** Run **Oversample** in order to balance our target variable and repeat the steps above, now with balanced data. Does it improve the performance of our model? 
- **5.** Now, run **Undersample** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?
- **6.** Finally, run **SMOTE** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?

---
# Solved LAB | Imbalanced
---

## **Load & View the data**

In this challenge, we will be working with Credit Card Fraud dataset.

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv

Metadata

- **distance_from_home:** the distance from home where the transaction happened.
- **distance_from_last_transaction:** the distance from last transaction happened.
- **ratio_to_median_purchase_price:** Ratio of purchased price transaction to median purchase price.
- **repeat_retailer:** Is the transaction happened from same retailer.
- **used_chip:** Is the transaction through chip (credit card).
- **used_pin_number:** Is the transaction happened by using PIN number.
- **online_order:** Is the transaction an online order.
- **fraud:** Is the transaction fraudulent. **0=legit** -  **1=fraud**

| Feature Name                     | Description                                                   | Data Type | Variable Type            | Action  | Role    |
|----------------------------------|---------------------------------------------------------------|-----------|--------------------------|---------|---------|
| `distance_from_home`               | Distance from home where the transaction occurred            | float64   | Numerical (Continuous)   | Scale   | Feature |
| `distance_from_last_transaction`   | Distance from previous transaction                           | float64   | Numerical (Continuous)   | Scale   | Feature |
| `ratio_to_median_purchase_price`   | Ratio of transaction amount to median purchase price         | float64   | Numerical (Continuous)   | Scale   | Feature |
| `repeat_retailer`                  | Transaction from same retailer (0 = No, 1 = Yes)             | float64   | Categorical (Binary)     | None    | Feature |
| `used_chip`                        | Transaction used chip (0 = No, 1 = Yes)                      | float64   | Categorical (Binary)     | None    | Feature |
| `used_pin_number`                  | Transaction used PIN (0 = No, 1 = Yes)                       | float64   | Categorical (Binary)     | None    | Feature |
| `online_order`                     | Transaction is online (0 = No, 1 = Yes)                      | float64   | Categorical (Binary)     | None    | Feature |
| `fraud`                            | Fraud label (0 = Legit, 1 = Fraud)                           | float64   | Categorical (Binary)     | None    | Target  |

In [ ]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
fraud = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/card_transdata.csv")
fraud.head()

In [ ]:
fraud.info()
#no nulls

In [ ]:
# unique values in each column
for col in fraud.columns:
    print(f"Unique values in '{col}': {fraud[col].nunique()}")
# no categorical columns, all are numerical

In [ ]:
# unique values in each column
for col in fraud.columns:
    print(f"Unique values in '{col}': {fraud[col].unique()}")
# no categorical columns, all are numerical

In [ ]:
fraud.duplicated().sum()
#no duplicates

---
## **Data Cleaning**
---

#### **Check the shape of your data**

In [ ]:
# Check the shape of the dataset*
print("Dataset Shape:", fraud.shape)
# number of rows 
print("Number of rows:", fraud.shape[0])
# number of columns
print("Number of columns:", fraud.shape[1])

#### **Check for data types**

In [ ]:
print("Data Types:")
display(fraud.dtypes)
# data type correctly assigned to each column

#### **Check for missing values**

In [ ]:
print("Missing Values:")
display(fraud.isnull().sum())
# no missing values in any column

---
## **Perform Train Test Split**
- split fraud dataset into train and test sets (stratify by target variable to maintain class distribution)

**Define target (y)**

In [ ]:
# define target variable
y = fraud["fraud"]

**Define features (X)**

In [ ]:
# define features: 
X = fraud.drop(["fraud"], axis=1)
print(f"Shape of data after dropping 'fraud': {X.shape}")
display(X.head())

**SPLIT**

In [ ]:
# define train-test split sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

#display the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

---
## **Feature Engineering**

1. Identity Categorical vs Numerical Features

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Boolean columns (already 0/1)
bool_cols = ['repeat_retailer', 'used_chip', 'used_pin_number', 'online_order']

# Categorical columns (more than 2 categories)
cat_cols = [] # no categorical columns, all are numerical other than the target variable

# Numerical columns
num_cols = ['distance_from_home', 'distance_from_last_transaction', 'ratio_to_median_purchase_price']

2. one hot encode categorical features (not boolean)

In [ ]:
ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

X_train_cat = pd.DataFrame(
    ohe.fit_transform(X_train[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_train.index
)

X_test_cat = pd.DataFrame(
    ohe.transform(X_test[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_test.index
)

3. Scale Numerical Columns

In [ ]:
scaler = StandardScaler()

X_train_num = pd.DataFrame(
    scaler.fit_transform(X_train[num_cols]),
    columns=num_cols,
    index=X_train.index
)

X_test_num = pd.DataFrame(
    scaler.transform(X_test[num_cols]),
    columns=num_cols,
    index=X_test.index
)

4. Convert Booleans to int (True=1 , False=0)

In [ ]:
# Boolean columns (already 0/1)
X_train_bool = X_train[bool_cols]
X_test_bool = X_test[bool_cols]

5. Combine & Save Train Test sets CSVs

In [ ]:
# Combine all features
X_train = pd.concat([X_train_num, X_train_bool, X_train_cat], axis=1)
X_test = pd.concat([X_test_num, X_test_bool, X_test_cat], axis=1)

# display the shapes of the resulting sets
print("X_train shape after encoding and scaling:", X_train.shape)
display(X_train.head())
print("X_test shape after encoding and scaling:", X_test.shape)
display(X_test.head())

print("y_train shape:", y_train.shape)
display(y_train.head())
print("y_test shape:", y_test.shape)
display(y_test.head())

# ---- Save preprocessed data to CSV files ----
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

---
## ** **

---
## **Steps:**

#### **Step 0.** Reset train and test sets to original

In [62]:
X_train = pd.read_csv("X_train.csv")
X_test = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv")
y_test = pd.read_csv("y_test.csv")
display(X_train.head())
display(y_train.head())
display(X_test.head())
display(y_test.head())

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
0,-0.353541,0.083049,-0.573726,1.0,1.0,0.0,1.0
1,-0.175683,-0.156580,0.315170,1.0,1.0,0.0,1.0
2,0.078467,-0.070319,-0.539590,1.0,0.0,0.0,1.0
3,-0.250188,-0.187940,-0.526985,1.0,0.0,0.0,0.0
4,0.839938,-0.010984,-0.192063,1.0,0.0,0.0,0.0

   fraud
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
0,-0.319315,-0.180502,-0.224534,1.0,0.0,0.0,1.0
1,2.609480,-0.182467,-0.243314,1.0,0.0,0.0,1.0
2,0.066344,-0.120437,-0.558983,1.0,1.0,0.0,1.0
3,-0.003421,21.803298,-0.453151,1.0,1.0,0.0,0.0
4,-0.390139,-0.172616,0.190981,0.0,0.0,0.0,0.0

   fraud
0    0.0
1    1.0
2    0.0
3    0.0
4    0.0

#### **Step 1.** What is the distribution of our target variable? Can we say we're dealing with an imbalanced dataset?

In [65]:
print("Train class distribution:")
print(y_train.iloc[:, 0].value_counts())
print(y_train.iloc[:, 0].value_counts(normalize=True))

print(100*'-')

print("\nTest class distribution:")
print(y_test.iloc[:, 0].value_counts())
print(y_test.iloc[:, 0].value_counts(normalize=True))

Train class distribution:
fraud
0.0    730078
1.0    730078
Name: count, dtype: int64
fraud
0.0    0.5
1.0    0.5
Name: proportion, dtype: float64
----------------------------------------------------------------------------------------------------

Test class distribution:
fraud
0.0    182519
1.0     17481
Name: count, dtype: int64
fraud
0.0    0.912595
1.0    0.087405
Name: proportion, dtype: float64

---
#### **Step 2.** Train a LogisticRegression.

In [66]:
# Train Logistic Regression
from sklearn.linear_model import LogisticRegression


log_regression = LogisticRegression(
    # class_weight="balanced", # not using class_weight here since we will apply resampling techniques later
    max_iter=1000,
    random_state=42
)

# Fit the model
log_regression.fit(X_train, y_train)

c:\Users\sboub\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(max_iter=1000, random_state=42)

---
#### **Step 3.** Evaluate your model. Take in consideration class importance, and evaluate it by selection the correct metric.

Since this is a fraud detection problem, the classes are not equally important.

Catching fraud (1) is more important than correctly predicting legitimate transactions (0).

That means:
- ❌ Accuracy is NOT appropriate
- ✅ Recall (Fraud class) is very important
- ✅ Precision is important (to avoid too many false alarms)
- ✅ F1-score (fraud class)
- ✅ PR-AUC (best for imbalanced datasets)
- ✅ ROC-AUC

🎯 Which Metric Should We Focus On?

In fraud detection:
- If you care about catching as many frauds as possible → **Recall**
- If false fraud alerts are expensive → **Precision**
- If you want balance → **F1-score**

For imbalanced datasets → **PR-AUC** is the most informative

🔥 Usually the Primary metric = **Recall (fraud class)** or **PR-AUC**

In [67]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    average_precision_score,
    roc_auc_score,
    confusion_matrix
)

# Predictions
y_train_pred = log_regression.predict(X_train)
y_test_pred = log_regression.predict(X_test)

y_train_proba = log_regression.predict_proba(X_train)[:, 1]
y_test_proba = log_regression.predict_proba(X_test)[:, 1]

print("=== LOGISTIC REGRESSION RESULTS ===")

# Accuracy
print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy :", accuracy_score(y_test, y_test_pred))

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_test_pred))

# PR AUC and ROC AUC
print("PR AUC:", average_precision_score(y_test, y_test_proba))
print("ROC-AUC:", roc_auc_score(y_test, y_test_proba))

# Train vs Test ROC AUC
print("\nTrain vs Test ROC AUC:\n")
print("Train ROC AUC:", roc_auc_score(y_train, y_train_proba))
print("Test ROC AUC :", roc_auc_score(y_test, y_test_proba))

# Confusion Matrix
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_test_pred))

# Overfitting Check
print("\nAccuracy Gap:",
      accuracy_score(y_train, y_train_pred) - accuracy_score(y_test, y_test_pred))

print("ROC AUC Gap:",
      roc_auc_score(y_train, y_train_proba) - roc_auc_score(y_test, y_test_proba))

=== LOGISTIC REGRESSION RESULTS ===
Train Accuracy: 0.9413466780261835
Test Accuracy : 0.93478

Classification Report:

              precision    recall  f1-score   support

         0.0       0.99      0.93      0.96    182519
         1.0       0.58      0.95      0.72     17481

    accuracy                           0.93    200000
   macro avg       0.79      0.94      0.84    200000
weighted avg       0.96      0.93      0.94    200000

PR AUC: 0.7574109963639821
ROC-AUC: 0.9795228512709144

Train vs Test ROC AUC:

Train ROC AUC: 0.9794233480302397
Test ROC AUC : 0.9795228512709144

Confusion Matrix:

[[170384  12135]
 [   909  16572]]

Accuracy Gap: 0.006566678026183492
ROC AUC Gap: -9.950324067475869e-05

---
#### **Step 4.** Run **Oversample** in order to balance our target variable and repeat the steps above, now with balanced data. Does it improve the performance of our model?

**Install**

In [ ]:
# pip install imbalanced-learn
#! pip install imbalanced-learn

**Run OverSample**

In [52]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score

# -------------------------
# Oversample train set only
# -------------------------
ros = RandomOverSampler(random_state=42)

X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

print("Before Oversampling:\n", y_train.value_counts())
print("\nAfter Oversampling:\n", y_train_resampled.value_counts())
X_train = X_train_resampled
y_train = y_train_resampled

Before Oversampling:
 fraud
0.0      730078
1.0       69922
Name: count, dtype: int64

After Oversampling:
 fraud
0.0      730078
1.0      730078
Name: count, dtype: int64

---
#### **Step 5.** Now, run **Undersample** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?

**Run UnderSample**

In [58]:
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score

# ---------------------------
# Undersample train set only
# ---------------------------
rus = RandomUnderSampler(random_state=42)

X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)

print("Before Undersampling:\n", y_train.value_counts())
print("\nAfter Undersampling:\n", y_train_resampled.value_counts())
X_train = X_train_resampled
y_train = y_train_resampled

Before Undersampling:
 fraud
0.0      730078
1.0       69922
Name: count, dtype: int64

After Undersampling:
 fraud
0.0      69922
1.0      69922
Name: count, dtype: int64

---
### **Step 6.** Finally, run **SMOTE** in order to balance our target variable and repeat the steps above (1-3), now with balanced data. Does it improve the performance of our model?

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score

# -----------------------------
# Apply SMOTE on train set only
# -----------------------------
smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Before SMOTE:\n", y_train.value_counts())
print("\nAfter SMOTE:\n", y_train_resampled.value_counts())
X_train = X_train_resampled
y_train = y_train_resampled

Before SMOTE:
 fraud
0.0      730078
1.0       69922
Name: count, dtype: int64

After SMOTE:
 fraud
0.0      730078
1.0      730078
Name: count, dtype: int64

---
### **Logistic Regression – Resampling Comparison**
Compare the impact of:
- No Sampling
- Random Oversampling
- Random Undersampling
- SMOTE

on Logistic Regression performance for fraud detection.

### 📊 Test Set Performance Comparison

| Method            | Recall (Fraud) | Precision (Fraud) | F1 (Fraud) | PR-AUC  | ROC-AUC |
|------------------|---------------|-------------------|------------|---------|---------|
| No Sampling      | 0.95          | 0.58              | 0.72       | 0.75721 | 0.97954 |
| Oversampling     | 0.95          | 0.58              | 0.72       | 0.75726 | 0.97953 |
| Undersampling    | 0.95          | 0.58              | 0.72       | 0.75638 | 0.97958 |
| SMOTE            | 0.95          | 0.58              | 0.72       | 0.75741 | 0.97952 |


### 🔎 Analysis

#### 1️⃣ Recall (Fraud Class)
All methods achieved: Recall = 0.95
No improvement in fraud detection rate.

---

#### 2️⃣ Precision (Fraud Class)
All methods:Precision = 0.58
No reduction in false positives.

---

#### 3️⃣ F1-Score
All methods: F1 = 0.72

---

#### 4️⃣ PR-AUC (Most Important for Imbalanced Data)

- No Sampling: 0.75721  
- Oversampling: 0.75726  
- Undersampling: 0.75638  
- SMOTE: 0.75741 (highest)

Difference between best and worst: ≈ 0.001

This difference is negligible and statistically insignificant.

---

## 🏆 Conclusion

All resampling techniques produced nearly identical results.

Technically:
- SMOTE has the highest PR-AUC (very small margin)

Practically:
- No Sampling performs just as well.

---

## 📌 Final Recommendation

For Logistic Regression on this dataset:

✅ Keep original data  
✅ No resampling needed  
✅ Model is already stable  
❌ Resampling adds complexity without performance gain  

---

## 🚀 Next Steps for Real Improvement

Instead of resampling, focus on:

1. Threshold tuning (optimize precision vs recall tradeoff)
2. Hyperparameter tuning (C regularization)
3. Trying tree-based models (Random Forest, XGBoost)
4. Feature engineering

---

### 🧠 Key Insight

The dataset is moderately imbalanced (~9% fraud),  
and Logistic Regression already separates classes effectively.

Resampling does not change the linear decision boundary significantly.